name: Build and push to site branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install hugo

      - name: Build website
        run: hugo

      - name: Backup generated files
        run: mv public /tmp/

      - name: Push new website
        working-directory: /tmp/public
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name  "github-action"
          git config --global init.defaultBranch "main"
          git init
          git add .
          git commit -m "Automatic update of website"
          git remote add deploy https://"$SUPER_SECRET"@github.com/Skallwar/skallwar.fr.git
          git push -f deploy site
